name: audit

on:
  schedule:
    - cron: "0 5 * * *" # daily 5AM

env:
  # not needed for audit
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  Audit:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/kit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.2.0
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      # check prod dependencies as these would affect users
      - run: pnpm audit --prod
